# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Test Status

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest

    permissions:
      actions: write
      contents: write
      deployments: write
      packages: none
      pull-requests: write
      security-events: write


    strategy:
      matrix:
        node-version: [18.x]

    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
          cache: yarn
      - run: yarn
      - run: yarn build
      - run: yarn test
      - name: Build docs
        run: |
          # Patch puppeteer launch to add --no-sandbox for CI
          sed -i 's/launch({ headless: true })/launch({ headless: true, args: ["--no-sandbox", "--disable-setuid-sandbox"] })/' node_modules/@rise4fun/docusaurus-remark-plugin-compile-code/lib/index.js
          yarn build:docs
      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        if: ${{ github.ref == 'refs/heads/main' }}
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: website/build
          force_orphan: true
    
    